### PR TITLE
[W.I.P #169665618] Improve email template

### PR DESCRIPTION
**Pull request by uxFeranmi**
### Made template responsive, and other improvements.

image

### CODE REVIEW

**Comment by uxFeranmi** [comment]
Feel free to pull this branch and pick up where I left off. I won't have time to work on it as I need to catch up on my Capstone project, among other things.

All that's left is to customize the displayed text using the data passed to the render method.

The available properties are clearly defined in function `notifyByEmail`.

**Review by LeanKhan — APPROVED** [review]
lgtm :)

**Comment by shonubijerry** [comment]
@LeanKhan Are you kidding me? 😄

**Review by shonubijerry — APPROVED** [review]

**Comment by LeanKhan** [comment]
> @LeanKhan Are you kidding me? 😄

😄 never too late boss

**Comment by uxFeranmi** [comment]
😂😂 Long time no ~see~ merge.

**Comment by shonubijerry** [comment]
> 😂😂 Long time no ~see~ merge.

And you ended up closing it

**Comment by uxFeranmi** [comment]
> And you ended up closing it

It looks like access control settings on this repo don't allow merging. I thought I should just close it instead.

**Comment by LeanKhan** [comment]
A lowkey reunion happened in the GitHub PR comments. Amazing 😅.

Hope everyone is fine! 🙂👋

**Comment by uxFeranmi** [comment]
Indeed. This was a nice throwback. 😊

**Pull request closed without merging**
