### PR TITLE
chore(code): remove duplicates in router.js

### PR DESCRIPTION
**Pull request by LeanKhan**
There were some undefined imports in the `router.js` file. Probably from my last merge conflict resolution. All tests pass basically.

image

### CODE REVIEW

**Comment by shonubijerry** [comment]
validateInviteId is different from validateInvite. While the former checks for bad input from req.params.inviteId and return a 400 error, the later checks if that invite exists in db and returns a 404 error if otherwise.

We should instead change validateInvite to validInvite just as we have validUser middleware.

**Comment by LeanKhan** [comment]
Yes, I am aware of that. Nothing was changed on that end. But I can change validateInvite to validInvite

**Comment by shonubijerry** [comment]
> Yes, I am aware of that. Nothing was changed on that end. But I can change validateInvite to validInvite

I think something was changed. In the routes I cannot find validateInviteId again. It should be the first middleware for all endpoints that takes in inviteId as a parapmeter (`req.params.inviteId`)

**Comment by shonubijerry** [comment]
Lets close this PR and just leave the existing code as is... but we can rename the `validateInvite` to `validInvite` to reduce ambiguity

**Comment by LeanKhan** [comment]
I have updated the code, my fault for not knowing the difference.

**Comment by LeanKhan** [comment]
We can close this, my latest PR has all the changes plus more. 
Thanks.

**Pull request closed without merging**
