### PR TITLE
169277746 admin can delete a users post

### PR DESCRIPTION
**Pull request by rexdavinci**

### CODE REVIEW

**Comment by rexdavinci** [comment]
Invite deleted with status 200 and corresponding message with title of deleted Invite

DELETE INVITE

**Review by shonubijerry — APPROVED** [review]

**Comment by rexdavinci** [comment]
Invalid Invite ID returns status 404
invalid id

**Comment by rexdavinci** [comment]
Invalid token or expired token returns status code 401

invalid token

**Comment by rexdavinci** [comment]
Non admin cannot delete returns status code 401
Non-admin cannot delete

**Comment by rexdavinci** [comment]
Tests - work in progress
detele test result

**Pull request closed without merging**
