### PR TITLE
Consume delete invite api

### PR DESCRIPTION
**Pull request by rexdavinci**
Requires inviteId

### CODE REVIEW

**Review by shonubijerry — APPROVED** [review]

**Comment by rexdavinci** [comment]
There are sample inviteIds inserted in the document as given in the seed DB. Input type of hidden is used to present the inviteId on the posts page.

**Comment by rexdavinci** [comment]
All posts are now fetched from database for admin and are deleted from database when admin clicks the delete button

**Comment by rexdavinci** [comment]
All posts are fetched from the DB (SEED DATA - NOT STATIC CONTENT)
image

**Comment by rexdavinci** [comment]
Clicking on Delete Icon removes the Invite under consideration and updates the DOM with the remainder Invites left in the Database

image

**Review by shonubijerry — APPROVED** [review]

**Pull request merged**
